### ISSUE TITLE
[緊急]masterじゃないと草が生えない件について

### ISSUE THREAD

**Issue by TUejima** [saezurucrow/ResponsiveDesign#9]
俺、草生増尾！トラックに引かれて異世界転生したら、masterじゃないと草が生えない世界にきてもう大変！城之内！ここで死んだらうんたらかんたらどうなるの！次回「Issuesで無理やり解決」コミットスタンバイ！

**Comment by saezurucrow** [comment]
あく進捗あげてマージしろ
